data:
  eval_database_files:  ['pickles/oxford/oxford_evaluation_database.pickle']
  eval_query_files: ['pickles/oxford/oxford_evaluation_query.pickle']
model:
  pointnet2:
    SAMPLING: [1024,256,64,16]
    KNN: [20,20,20,20]
    FEATURE_SIZE: [256,256,256,256]
    GROUP: 8
  aggregator:
    NAME: spvlad
    FEATURE_SIZE: [256,256,256,256]
    MAX_SAMPLES: [64,256,1024,4096]
    CLUSTER_SIZE: [1,4,16,64]
    OUTPUT_DIM: [256,256,256,256]
    GATING: True
