data:
  eval_database_files:  ['pickles/oxford/oxford_evaluation_database.pickle',
                        'pickles/MulRan/DCC_03_evaluation_database.pickle',
                        'pickles/MulRan/Riverside_02_evaluation_database.pickle',
                        'pickles/oxford/business_evaluation_database.pickle', 
                        'pickles/oxford/residential_evaluation_database.pickle', 
                        'pickles/oxford/university_evaluation_database.pickle']
  eval_query_files: ['pickles/oxford/oxford_evaluation_query.pickle',
                    null, 
                    null, 
                    'pickles/oxford/business_evaluation_query.pickle', 
                    'pickles/oxford/residential_evaluation_query.pickle', 
                    'pickles/oxford/university_evaluation_query.pickle']
  pin_memory: False
model:
  name: PointNetVlad
train:
  batch_size: 16
  batch_size_limit: 16
  optimizer:
    lr: 0.0001
    epochs: 80
    scheduler_milestones: [40,60]
eval:
  frequency: -1